# Generated by Django 3.2.3 on 2022-01-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_delete_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='MyProject',
        ),
    ]
